### ISSUE TITLE
Any updates for current version of serilog? Or it's just works?

### ISSUE THREAD

**Issue by SuddenGunter** [b00ted/serilog-sinks-postgresql#10]
Hi
Latest commit in this repo was 10 months ago.
Will there be any updates for current version of serilog? Or it just works?

**Comment by b00ted** [comment]
Is there any reasonable arguments to bump up serilog dependency version? It works fine for me with serilog 2.5.0, but I've not tested it with later versions.

**Comment by SuddenGunter** [comment]
Thank you for an answer)
I was just afraid if the project isn't abandoned or something like that.
Is there are any sql snippets for db creation?
or sink will create it by itself?

**Comment by b00ted** [comment]
table auto creation added in 1.2
