### ISSUE TITLE
Serilog.Sinks.PostgreSQL is not working along with Npgsql package version 4.0.0

### ISSUE THREAD

**Issue by reponemec** [b00ted/serilog-sinks-postgresql#11]
In my ASP.Net Core application, a Serilog.Sinks.PostgreSQL sink works fine along with Npgsql package version lower then 4.0.0, but it does not work along with Npgsql package version 4.0.0. Along with Npgsql package version 4.0.0 it does not save log events into the database nor throw any exceptions into the SelfLog.
My application targets NET.Core 2.1..

**Comment by b00ted** [comment]
There is a breaking change in bulk insert api in Npgsql 4.0 since 3.x. You can try switch to insert statements by setting 'useCopy' parameter to false.

**Comment by reponemec** [comment]
Exactly. It seems the new (v. 4.x) NpgsqlBinaryImporter.Complete() operation is that a little devil (but it has its sense, of course). I think class PostgreSQLSink should explicitly call this operation on finish its work.
OK, I'll try a second way you mentioned, but I'm afraid of a performance degradation.
Do you plan to publish a new version of Serilog.Sinks.PostgreSQL referencing 4.x of Npsql?

**Comment by reponemec** [comment]
I'm afraid I cannot use useCopy = false due to https://github.com/b00ted/serilog-sinks-postgresql/issues/12 issue.
