### ISSUE TITLE
Sink throws an exception if camel casing convention for column names is used

### ISSUE THREAD

**Issue by reponemec** [b00ted/serilog-sinks-postgresql#12]
If I use a camel casing naming convention for my log table and its columns (e.g. I've got a table named LogEvent which has a column named Message), I must use a quote marks around that names when I'm sending them to your API, that is OK. But it works fine only in case of useCopy = true. In case of useCopy = false it leads to Exception at command.ExecuteNonQuery() line of code in ProcessEventsByInsertStatements operation because command.CommandText contains wrong insert string syntax including that quote marks arround a parameter name: INSERT INTO "dbo"."LogEvent" ("Message") VALUES (:"Message").

**Comment by b00ted** [comment]
fixed in version 1.1.1
