### ISSUE TITLE
Unable to write to properties column for JSON datatype

### ISSUE THREAD

**Issue by ferrerojosh** [b00ted/serilog-sinks-postgresql#2]
I get the following error whenever I map properties to a JSON column.

> 2017-05-27T02:07:03.9952458Z Unable to write 2 log events to the database due to following error: 22P02: invalid input syntax for type json

Also if I change the datatype to text output is:

>{"Timestamp":"2017-05-27T10:14:52.2095661+08:00","Level":"Information","MessageTemplate":"{State:l}","Properties":{"State":"Saved 1 entities to in-memory store.","EventId":{"Id":1},"SourceContext":"Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryDatabase"},"Renderings":{"State":[{"Format":"l","Rendering":"Saved 1 entities to in-memory store."}]}}

There's a strange character at the start.

**Comment by b00ted** [comment]
I suppose that you use LogEventSerializedColumnWriter here. Could you, please, try to do the same thing with    PropertiesColumnWriter? 
And disable copy command using by
`.WriteTo.PostgreSQL(connectionString, tableName, columnProps, useCopy: false)`

**Comment by ferrerojosh** [comment]
```C#
            IDictionary<string, ColumnWriterBase> columnWriters = new Dictionary<string, ColumnWriterBase>
            {
                {"message", new RenderedMessageColumnWriter() },
                {"message_template", new MessageTemplateColumnWriter() },
                {"level", new LevelColumnWriter(true, NpgsqlDbType.Varchar) },
                {"raise_date", new TimeStampColumnWriter() },
                {"exception", new ExceptionColumnWriter() },
                {"properties", new PropertiesColumnWriter() },
                {"machine_name", new SinglePropertyColumnWriter("MachineName", PropertyWriteMethod.Raw) }
            };

            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.PostgreSQL(connectionStr, logTable, columnWriters, useCopy: false)
                .WriteTo.LiterateConsole()
                .CreateLogger();
```

Still having the same error.

**Comment by b00ted** [comment]
Could you, please, provide you environment description (properties column type (JSON or JSONB), postgresql version, .net version, operating system, database encoding)

**Comment by ferrerojosh** [comment]
Operating System - Windows 10 version 1703, build 15063.296
.NET Version - .NET Core 1.1
Database - PostgreSQL 9.6.2
Database Encoding - UTF8
Column Type - JSON

**Comment by b00ted** [comment]
Both LogEventSerializedColumnWriter and PropertiesColumnWriter use JSONB column type by default. Did you try set the column type explicitly in constructor?
`new PropertiesColumnWriter(NpgsqlDbType.Json)`

**Comment by ferrerojosh** [comment]
Adding NpgsqlDbType.Json as argument to PropertiesColumnWriter resolved the problem.
