### ISSUE TITLE
An open source log event viewer

### ISSUE THREAD

**Issue by reponemec** [b00ted/serilog-sinks-postgresql#20]
Is there a (an open source) log event viewer compatible with this sink? Ideally as great as [Seq](https://docs.getseq.net/docs/using-serilog) :-).

**Comment by manisero** [comment]
Yes, there is something called PostgreSQL (https://www.postgresql.org/, source: https://github.com/postgres/postgres). For GUI viewer, see pgAdmin (https://www.pgadmin.org/, source: https://www.pgadmin.org/download/pgadmin-4-source-code/). Hope this helps :)
