### ISSUE TITLE
Custom Columns

### ISSUE THREAD

**Issue by ssonnenwald** [b00ted/serilog-sinks-postgresql#23]
I'm having a problem with custom columns.  I have a section in my appsettings.json file for Serilog that has columns defined, but it seems that when it creates the log table it just ignores all of the column stuff.  Can you lend some help here.  Does this work or not???  What is it that is perhaps wrong with this config?

My config:
"Serilog": {
    "Using": [ "PostgreSQL" ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Debug"
      }
    },
    "WriteTo": [
      {
        "Name": "PostgreSQL",
        "Args": {
          "connectionString": "User ID=;Password=;Host=localhost;Port=5432;Database=",
          "needAutoCreateTable": "true",
          "schemaName": "banklink",
          "tableName": "Logs",
          "columnOptionsSection": {
            "removeStandardColumns": [ "Message", "Message_Tempate", "Level", "Timestamp", "Exception", "Log_Event" ],
            "customColumns": [
              {
                "ColumnName": "message",
                "DataType": "text",
                "AllowNull": true
              },
              {
                "ColumnName": "message_template",
                "DataType": "text",
                "AllowNull": true
              },
              {
                "ColumnName": "logcode",
                "DataType": "integer",
                "AllowNull": true
              },
              {
                "ColumnName": "level",
                "DataType": "integer",
                "AllowNull": true
              },
              {
                "ColumnName": "timestamp",
                "DataType": "timestamp",
                "AllowNull": true
              },
              {
                "ColumnName": "exception",
                "DataType": "text",
                "AllowNull": true
              },
              {
                "ColumnName": "log_event",
                "DataType": "jsonb",
                "AllowNull": true
              }
            ]
          }
        }
      }
    ]
  },

**Comment by b00ted** [comment]
Unfortunately sink does not support reading settings from config file.
See issue #9
