### ISSUE TITLE
Read from appSettings.json configuration not working

### ISSUE THREAD

**Issue by ajitgoel** [b00ted/serilog-sinks-postgresql#29]
The system is not autocreating logs table and logging errors in my postgres database. What am I missing? 

```
public class Program
  {
    public static void Main(string[] args)
    {
      var path = Directory.GetCurrentDirectory();
      var environmentName =Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production";

      var configuration = new ConfigurationBuilder()
        .SetBasePath(path)
        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
        .AddJsonFile($"appsettings.{environmentName}.json", optional: true, reloadOnChange: true)
        .AddEnvironmentVariables()
        .Build();
      Log.Logger = new LoggerConfiguration()
        .Enrich.FromLogContext()
        .ReadFrom.Configuration(configuration)
        .CreateLogger();
      try
      {
        var iWebHost = CreateWebHostBuilder(args).Build();
        iWebHost.Run();
      }
      finally
      {
        Log.CloseAndFlush();
      }
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseSerilog();
  }

```
```
"Serilog": {
    "Using": [ "Serilog.Sinks.PostgreSQL" ],
    "MinimumLevel": "Warning",
    "WriteTo": [
      {
        "Name": "PostgreSQL",
        "Args": {
          "connectionString": "Server=localhost;Port=5432;Database=postgres;User Id=postgres;Password=<password>;Pooling=true;Minimum Pool Size=1;Maximum Pool Size=100;",
          "tableName": "Logs",
          "autoCreateSqlTable": true,
          "batchPostingLimit": 1 
        }
      }
    ]
  }
```

**Comment by harikumarst** [comment]
public class Program
    {
        public static void Main(string[] args)
        {
            try
            {      
                CreateWebHostBuilder(args).Build().Run();
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                  .UseStartup<Startup>().UseSerilog((hostingContext, loggerConfiguration) =>
                  { 
                      loggerConfiguration                    
                      .ReadFrom.Configuration(hostingContext.Configuration);                          
                  });
        }
    }

"Serilog": {    
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Verbose",
        "System": "Verbose"
      }
    },
    "WriteTo": [ 
        {
          "Name": "PostgreSQL",
          "Args": {
            "connectionString": "Server=localhost;Port=5432;Database=****;User Id=*****;Password=***",
            "restrictedToMinimumLevel": "Warning",
            "needAutoCreateTable": "true",
            "respectCase": "true",
            "schemaName": "Logs",
            "tableName": "Application_Logs"
          }        
      }
    ]
  } 

For me with the above code, the tables are getting created and able to log.

**Comment by ajitgoel** [comment]
i had to add a `"Using": [ "Serilog.Sinks.PostgreSQL" ]` line to fix a runtime exception above.
I have changed the code as above but the database is still not logging error logs. Is there a way to find out tracing in Serilog \ Serilogs.Sinks.Postgre to find out what the issue could be?

**Comment by harikumarst** [comment]
Kindly refer the below link for debugging the serilog
https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

**Comment by ajitgoel** [comment]
I added code to debug serilog and the only errors that I can see in my debug window are. 

The thread 0x29c8 has exited with code 0 (0x0).
The thread 0x2e54 has exited with code 0 (0x0).
The thread 0x3cb4 has exited with code 0 (0x0).
The thread 0x2cbc has exited with code 0 (0x0).
The thread 0x3de8 has exited with code 0 (0x0).

I will go ahead by just logging using Serilog Postgres sink but not using the Appsettings to store the Serilog configuration.

**Comment by ajitgoel** [comment]
I was able to fix this issue by adding the following code: 

**Program.cs:**
```
 var configuration = new ConfigurationBuilder()
        .SetBasePath(path)
        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
        .AddJsonFile($"appsettings.{environmentName}.json", optional: true, reloadOnChange: true)
        .AddEnvironmentVariables()
        .Build();
      Log.Logger = new LoggerConfiguration().
        Enrich.FromLogContext().
        ReadFrom.Configuration(configuration).
        CreateLogger();

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
       WebHost.CreateDefaultBuilder(args)
       .UseStartup<Startup>()
       .UseSerilog();

```


**AppSettings.json:**
```
"Serilog": {
    "Using": [ "Serilog.Sinks.PostgreSQL" ],
    "MinimumLevel": "Warning",
    "WriteTo": [
      {
        "Name": "PostgreSQL",
        "Args": {
          "connectionString": "Server=localhost;Port=5432;Database=postgres;User Id=postgres;Password=<password>;Pooling=true;Minimum Pool Size=1;Maximum Pool Size=100;",
          "tableName": "Logs",
          "needAutoCreateTable": true,
          "batchPostingLimit": 1
        }
      }
    ]
  }
```
