### ISSUE TITLE
add an option for autoCreateSqlTable

### ISSUE THREAD

**Issue by Meir017** [b00ted/serilog-sinks-postgresql#3]
@b00ted  Similar to what [serilog-sinks-mssqlserver](https://github.com/serilog/serilog-sinks-mssqlserver/blob/dev/src/Serilog.Sinks.MSSqlServer/Sinks/MSSqlServer/MSSqlServerSink.cs#L102) has.

**Comment by b00ted** [comment]
Added in version 1.2
