### ISSUE TITLE
Configuration NullReferenceException from unmanaged code

### ISSUE THREAD

**Issue by Kimmova** [b00ted/serilog-sinks-postgresql#36]
When using the json configuration option to specify columns using the `configurationPath` property. 
I encountered a `NullReferenceException` in my use case, where the assembly containing the Serilog setup was called from an IIS module, resulting in `Assembly.GetEntryAssembly()` being null. 
This causes an exception on https://github.com/b00ted/serilog-sinks-postgresql/blob/master/Serilog.Sinks.PostgreSQL.Configuration/ConfigurationReader.cs#L32 when calling `.ExportedTypes` on an object that is null.

I believe the issue is caused by the calling assembly being an unmanaged application, according to MSDN docs (https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly):
```
The GetEntryAssembly method can return null when a managed assembly has been loaded from an unmanaged application.
```

I propose the following change to support this scenario (https://github.com/b00ted/serilog-sinks-postgresql/blob/master/Serilog.Sinks.PostgreSQL.Configuration/ConfigurationReader.cs#L154).

Current implementation:
```csharp
var assemblies = new List<Assembly> { typeof(PostgreSQLSink).Assembly, Assembly.GetEntryAssembly() };
```

Revised implementation:
```csharp
var assemblies = new List<Assembly> { typeof(PostgreSQLSink).Assembly, Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly() };
```

This should not break any existing functionality, but will open up support for use-cases like this.

@b00ted Should I make a PR, or would you like to implement this yourself?

As a temporary fix, I have moved configuration to code instead of my .json file.

Thanks in advance!

**Comment by b00ted** [comment]
Thank you for detailed description! Fixed in 1.0.1
