### ISSUE TITLE
Read from json configuration?

### ISSUE THREAD

**Issue by reponemec** [b00ted/serilog-sinks-postgresql#9]
Is there a built-in support for settings this sink via appsettings.json in the "Serilog" subsection? In a similar manner as in the case of Serilog.Sinks.File, for example.
I cannot imagine a part for columnWriters argument. Please provide an example.

**Comment by b00ted** [comment]
Unfortunately Microsoft.Extensions.Configuration does not allow to read values without parameterless constructor. Serilog.Settings.Configuration have a realization for reading of Action<LoggerConfiguration> and Action<LoggerSinkConfiguration> only. So you can't read it from appsettings for now.

**Comment by SeppPenner** [comment]
This is possible now, I would assume: https://github.com/serilog/serilog-settings-configuration. This guy did it, for example: https://github.com/DixonDs/serilog-sinks-teams

**Comment by XanNava** [comment]
I would like to know if this is possible, or if this sink needs to be updated. Likewise could we get an example of how to use this?

Without this I don't see how this could be production ready.

**Comment by XanNava** [comment]
I actually accomplished this, here is my json.
```json
{
  "Serilog": {
    "Using":  [],
    "WriteTo": [
      {
        "Name": "PostgreSQL",
        "Args": {
          "connectionString": "User ID=XXXX;Password=XXXX;Host=XXXX",
          "tableName": "XXXX",
          "useCopy": false,
          "schemaName": "XXXX",
          "needAutoCreateTable": true,
          "respectCase": true
        }
      }
    ]
  }
}
```
Not schemaName was public for me/default for postgre, and "useCopy" had to be false else there where errors.

**Comment by SeppPenner** [comment]
My sink under https://github.com/SeppPenner/SerilogSinkForPostgreSQL is maintained (At least, I try as best as I can :P).

**Comment by reponemec** [comment]
> My sink under https://github.com/SeppPenner/SerilogSinkForPostgreSQL is maintained (At least, I try as best as I can :P).

Is there a support for table columns definition via JSON file in that sink?

**Comment by reponemec** [comment]
I guess I see it already.

**Comment by SeppPenner** [comment]
> 
> 
> > My sink under https://github.com/SeppPenner/SerilogSinkForPostgreSQL is maintained (At least, I try as best as I can :P).
> 
> Is there a support for table columns definition via JSON file in that sink?

Should be supported :)

**Comment by b00ted** [comment]
Finally get this works. [https://github.com/b00ted/serilog-sinks-postgresql#configuration](Here) is the docs
